[versions]
asm = "9.0"
kotlin = "1.6.0"

[libraries]
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
asmTree = { module = "org.ow2.asm:asm-tree", version.ref = "asm" }
kotlinGradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin" }
kotlinBinaryCompatibility = "org.jetbrains.kotlinx:binary-compatibility-validator:0.8.0"
okhttpLogging = "com.squareup.okhttp3:logging-interceptor:4.9.0"
retrofit = "com.squareup.retrofit2:retrofit:2.9.0"
detekt = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.18.1"
